In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [2]:
echo_message = pd.read_csv("can_log.csv", delimiter = ",")
echo_message

Timestamp Atribration_id  dlc              data
0     1.757524e+09     0x18820810    5        020a016f09
1     1.757524e+09     0x18820810    3            070101
2     1.757524e+09     0x18820810    8  102045204f464620
3     1.757524e+09     0x18820810    4          00202000
4     1.757524e+09     0x18820810    5        0200007a20
...            ...            ...  ...               ...
3798  1.757524e+09     0x19000410    3            0a1fff
3799  1.757524e+09     0x19000410    3            021fff
3800  1.757524e+09     0x19000410    3            071fff
3801  1.757524e+09     0x19000410    3            101fff
3802  1.757524e+09     0x18820810    1                12

[3803 rows x 4 columns]

In [3]:
echo_message.head(10)

Timestamp Atribration_id  dlc              data
0  1.757524e+09     0x18820810    5        020a016f09
1  1.757524e+09     0x18820810    3            070101
2  1.757524e+09     0x18820810    8  102045204f464620
3  1.757524e+09     0x18820810    4          00202000
4  1.757524e+09     0x18820810    5        0200007a20
5  1.757524e+09     0x18820810    5        02010c3b09
6  1.757524e+09     0x18820810    3            070101
7  1.757524e+09     0x19000410    3            021fff
8  1.757524e+09     0x18820810    8  10506d702020302e
9  1.757524e+09     0x18820810    4          00302500

In [4]:
unique_id, id_counts = np.unique(echo_message['Atribration_id'], return_counts = True)
print(unique_id)
print(id_counts)

['0x18820810' '0x19000410']
[1902 1901]


In [5]:
unique_dlc, dlc_counts = np.unique(echo_message['dlc'], return_counts = True)
print(unique_dlc)
print(dlc_counts)

[1 2 3 4 5 6 8]
[  30  144 2333  216  648  144  288]


In [6]:
unique_data, data_counts = np.unique(echo_message['data'], return_counts = True)
print(unique_data)
print(data_counts)

['00202000' '0020312000' '00302500' '00f84300' '0200007a20' '02010c3b09'
 '0201163b09' '020a016f09' '021fff' '023e0c3b09' '070101' '070202'
 '071fff' '0a0000000901' '0a00003b0001' '0a1fff' '0d00' '0d01' '0d1fff'
 '101e00' '101fff' '102045204f464620' '1020506b20202020'
 '10506d702020302e' '1074202020302e30' '12' '121fff']
[ 72  72  72  72 288  72  72  72 576  72 288  72 360  72  72 144  72  72
 144  72 648  72  72  72  72  30  29]


In [7]:
"""
So looking at the data, it seems that both the controller and the laser are communicating with each other and constantly echoing messages
on the CAN bus line. Since there are two atribution ids, it means that are two devices on the bus system. Must figure out which is which.
Once we figure out which is which, we can mimic the controller and send messages from the PiCAN hat.
"""

'\nSo looking at the data, it seems that both the controller and the laser are communicating with each other and constantly echoing messages\non the CAN bus line. Since there are two atribution ids, it means that are two devices on the bus system. Must figure out which is which.\nOnce we figure out which is which, we can mimic the controller and send messages from the PiCAN hat.\n'

In [8]:
Device_one = echo_message[echo_message['Atribration_id'] == '0x18820810']

Device_two = echo_message[echo_message['Atribration_id'] == '0x19000410']

print(len(Device_one))
print(len(Device_two))

1902
1901


In [22]:
# So now getting all the unique messages from each device
device_one_data, device_one_dcounts = np.unique(Device_one['data'], return_counts = True)

print(device_one_data)
print(device_one_dcounts)
print(len(device_one_data))

['00202000' '0020312000' '00302500' '00f84300' '0200007a20' '02010c3b09'
 '0201163b09' '020a016f09' '023e0c3b09' '070101' '070202' '0a0000000901'
 '0a00003b0001' '0d00' '0d01' '101e00' '102045204f464620'
 '1020506b20202020' '10506d702020302e' '1074202020302e30' '12']
[ 72  72  72  72 288  72  72  72  72 288  72  72  72  72  72  72  72  72
  72  72  30]
21


In [27]:
device_two_data, device_two_dcounts = np.unique(Device_two['data'], return_counts = True)

print(device_two_data)
print(device_two_dcounts)
print(len(device_two_data))

['021fff' '071fff' '0a1fff' '0d1fff' '101fff' '121fff']
[576 360 144 144 648  29]
6


In [11]:
# Now importing the other data files to cross ananlyze the data
no_controller = pd.read_csv('can_log_no_controller.csv', delimiter = ',')
change_burst_mode = pd.read_csv('can_log_change_burst_mode.csv', delimiter = ',')


In [12]:
# The data for the no_controller dataset
no_controller.head(10)

Timestamp Atribration_id  dlc  data
0  1.757527e+09     0x18820810    1    12
1  1.757527e+09     0x18820810    1    12
2  1.757527e+09     0x18820810    1    12
3  1.757527e+09     0x18820810    1    12
4  1.757527e+09     0x18820810    1    12
5  1.757527e+09     0x18820810    1    12
6  1.757527e+09     0x18820810    1    12
7  1.757527e+09     0x18820810    1    12
8  1.757527e+09     0x18820810    1    12
9  1.757527e+09     0x18820810    1    12

In [39]:
change_burst_mode.head(10)

Timestamp Atribration_id  dlc              data
0  1.757528e+09     0x18820810    3            07020f
1  1.757528e+09     0x18820810    8  102020436f6e7469
2  1.757528e+09     0x18820810    7    006e756f757300
3  1.757528e+09     0x18820810    3            070202
4  1.757528e+09     0x18820810    3            101e00
5  1.757528e+09     0x19000410    3            071fff
6  1.757528e+09     0x19000410    3            101fff
7  1.757528e+09     0x19000410    3            101fff
8  1.757528e+09     0x19000410    3            071fff
9  1.757528e+09     0x19000410    3            101fff

In [14]:
# Unique ID's for controller only. Looking at the data it seems that it echos at 2Hz
nc_unique_ID, nc_counts_ID = np.unique(no_controller['Atribration_id'], return_counts = True)
print(nc_unique_ID)
print(nc_counts_ID)

['0x18820810']
[30]


In [15]:
nc_unique_data, nc_counts_data = np.unique(no_controller['data'], return_counts = True)
print(nc_unique_data)
print(nc_counts_data)

#If no controller is connected, the laser just echos a 1 bit message. 

[12]
[30]


In [16]:
# For the command lets see how the data differs. Now we know that the laser ID is '0x18820810' and the controller is '0x19000410'
unique, count = np.unique(change_burst_mode['Atribration_id'], return_counts = True)
print(unique)

['0x18820810' '0x19000410']


In [17]:
laser_messages = change_burst_mode[change_burst_mode['Atribration_id'] == '0x18820810']
controller_messages = change_burst_mode[change_burst_mode['Atribration_id'] == '0x19000410']

print(len(laser_messages))
print(len(controller_messages))

775
818


In [21]:
laser_unique_data, laser_data_counts = np.unique(laser_messages['data'], return_counts = True)
print(laser_unique_data)
print(laser_data_counts)
print(len(laser_unique_data))

['00206d6f646500' '00207472696700' '00656e67746800' '006e756f757300'
 '006f646500' '0200007a20' '02010c6714' '02010c6f14' '03' '0500' '0503'
 '070101' '07010b' '070202' '07020f' '070b02' '0a000a790a01'
 '0b720c081401' '0c740f040101' '0f0000000000' '0f010c700a00'
 '0f010c700a01' '0f070e250904' '101e00' '1020204275727374'
 '102020436f6e7469' '104275727374204c' '104275727374204d' '104d454e5500'
 '12']
[ 45  17   4  54   7   4   4   4  11   3   3   4   4 144 116   7   7   4
   4   4   3   4   3 143  62  54   4   7   4  41]
30


In [26]:
controller_unique_data, controller_data_counts = np.unique(controller_messages['data'], return_counts = True)
print(controller_unique_data)
print(controller_data_counts)
print(len(controller_unique_data))

['021ffb' '031fdf' '031ffb' '051fdf' '071fbf' '071fdf' '071fef' '071ffb'
 '071fff' '0a1fdf' '0a1ffb' '0b1ffb' '0c1ffb' '0f1fdf' '0f1ffb' '101fbf'
 '101fdf' '101fef' '101ffb' '101fff' '121fbf' '121fdf' '121fef' '121ffb'
 '121fff']
[ 12   3   8   6  10  12  13  14 225   3   4   4   4   6   8  17  21  22
  22 319   4   9   5   4  63]
25


In [28]:
# Now to compare and contrast the messages for each device. Starting with the laser
laser_idle = Device_one.copy()
controller_idle = Device_two.copy()

# The data for when the device is sending messages
laser_messages
controller_messages

Timestamp Atribration_id  dlc    data
5     1.757528e+09     0x19000410    3  071fff
6     1.757528e+09     0x19000410    3  101fff
7     1.757528e+09     0x19000410    3  101fff
8     1.757528e+09     0x19000410    3  071fff
9     1.757528e+09     0x19000410    3  101fff
...            ...            ...  ...     ...
1584  1.757528e+09     0x19000410    3  071fff
1585  1.757528e+09     0x19000410    3  101fff
1587  1.757528e+09     0x19000410    3  121fff
1590  1.757528e+09     0x19000410    3  071fff
1591  1.757528e+09     0x19000410    3  101fff

[818 rows x 4 columns]

In [35]:
# Compare the unique indecies for each one and append the different ones to a list
similar_laser = []
different_laser = []

for message in laser_unique_data:
    if message in device_one_data:
        similar_laser.append(message)
    else:
        different_laser.append(message)

print(similar_laser, 'These are commands that are similar')
print(different_laser, 'These are commands that are different')

['0200007a20', '070101', '070202', '101e00', '12'] These are commands that are similar
['00206d6f646500', '00207472696700', '00656e67746800', '006e756f757300', '006f646500', '02010c6714', '02010c6f14', '03', '0500', '0503', '07010b', '07020f', '070b02', '0a000a790a01', '0b720c081401', '0c740f040101', '0f0000000000', '0f010c700a00', '0f010c700a01', '0f070e250904', '1020204275727374', '102020436f6e7469', '104275727374204c', '104275727374204d', '104d454e5500'] These are commands that are different


In [37]:
similar_controller = []
different_controller = []

for message in controller_unique_data:
    if message in device_two_data:
        similar_controller.append(message)
    else:
        different_controller.append(message)

print(similar_controller, 'These are the similar messages')
print(different_controller, 'These are the different messages')

['071fff', '101fff', '121fff'] These are the similar messages
['021ffb', '031fdf', '031ffb', '051fdf', '071fbf', '071fdf', '071fef', '071ffb', '0a1fdf', '0a1ffb', '0b1ffb', '0c1ffb', '0f1fdf', '0f1ffb', '101fbf', '101fdf', '101fef', '101ffb', '121fbf', '121fdf', '121fef', '121ffb'] These are the different messages
