In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [2]:
echo_message = pd.read_csv("can_log.csv", delimiter = ",")
echo_message

Timestamp Atribration_id  dlc              data
0     1.757524e+09     0x18820810    5        020a016f09
1     1.757524e+09     0x18820810    3            070101
2     1.757524e+09     0x18820810    8  102045204f464620
3     1.757524e+09     0x18820810    4          00202000
4     1.757524e+09     0x18820810    5        0200007a20
...            ...            ...  ...               ...
3798  1.757524e+09     0x19000410    3            0a1fff
3799  1.757524e+09     0x19000410    3            021fff
3800  1.757524e+09     0x19000410    3            071fff
3801  1.757524e+09     0x19000410    3            101fff
3802  1.757524e+09     0x18820810    1                12

[3803 rows x 4 columns]

In [3]:
echo_message.head(10)

Timestamp Atribration_id  dlc              data
0  1.757524e+09     0x18820810    5        020a016f09
1  1.757524e+09     0x18820810    3            070101
2  1.757524e+09     0x18820810    8  102045204f464620
3  1.757524e+09     0x18820810    4          00202000
4  1.757524e+09     0x18820810    5        0200007a20
5  1.757524e+09     0x18820810    5        02010c3b09
6  1.757524e+09     0x18820810    3            070101
7  1.757524e+09     0x19000410    3            021fff
8  1.757524e+09     0x18820810    8  10506d702020302e
9  1.757524e+09     0x18820810    4          00302500

In [4]:
unique_id, id_counts = np.unique(echo_message['Atribration_id'], return_counts = True)
print(unique_id)
print(id_counts)

['0x18820810' '0x19000410']
[1902 1901]


In [5]:
unique_dlc, dlc_counts = np.unique(echo_message['dlc'], return_counts = True)
print(unique_dlc)
print(dlc_counts)

[1 2 3 4 5 6 8]
[  30  144 2333  216  648  144  288]


In [6]:
unique_data, data_counts = np.unique(echo_message['data'], return_counts = True)
print(unique_data)
print(data_counts)

['00202000' '0020312000' '00302500' '00f84300' '0200007a20' '02010c3b09'
 '0201163b09' '020a016f09' '021fff' '023e0c3b09' '070101' '070202'
 '071fff' '0a0000000901' '0a00003b0001' '0a1fff' '0d00' '0d01' '0d1fff'
 '101e00' '101fff' '102045204f464620' '1020506b20202020'
 '10506d702020302e' '1074202020302e30' '12' '121fff']
[ 72  72  72  72 288  72  72  72 576  72 288  72 360  72  72 144  72  72
 144  72 648  72  72  72  72  30  29]


In [11]:
"""
So looking at the data, it seems that both the controller and the laser are communicating with each other and constantly echoing messages
on the CAN bus line. Since there are two atribution ids, it means that are two devices on the bus system. Must figure out which is which.
Once we figure out which is which, we can mimic the controller and send messages from the PiCAN hat.
"""

'\nSo looking at the data, it seems that both the controller and the laser are communicating with each other and constantly echoing messages\non the CAN bus line. Since there are two atribution ids, it means that are two devices on the bus system. Must figure out which is which.\nOnce we figure out which is which, we can mimic the controller and send messages from the PiCAN hat.\n'

In [12]:
Device_one = echo_message[echo_message['Atribration_id'] == '0x18820810']

Device_two = echo_message[echo_message['Atribration_id'] == '0x19000410']

In [14]:
# So now getting all the unique messages from each device
device_one_data, device_one_dcounts = np.unique(Device_one['data'], return_counts = True)

print(device_one_data)
print(device_one_dcounts)

['00202000' '0020312000' '00302500' '00f84300' '0200007a20' '02010c3b09'
 '0201163b09' '020a016f09' '023e0c3b09' '070101' '070202' '0a0000000901'
 '0a00003b0001' '0d00' '0d01' '101e00' '102045204f464620'
 '1020506b20202020' '10506d702020302e' '1074202020302e30' '12']
[ 72  72  72  72 288  72  72  72  72 288  72  72  72  72  72  72  72  72
  72  72  30]


In [16]:
device_two_data, device_two_dcounts = np.unique(Device_two['data'], return_counts = True)

print(device_two_data)
print(device_two_dcounts)

['021fff' '071fff' '0a1fff' '0d1fff' '101fff' '121fff']
[576 360 144 144 648  29]
